version: "3.8"
services:
  node1:
    build: .
    ports:
      - "8081:8080"
    environment:
      - NODE_ID=node1

  node2:
    build: .
    ports:
      - "8082:8080"
    environment:
      - NODE_ID=node2

  node3:
    build: .
    ports:
      - "8083:8080"
    environment:
      - NODE_ID=node3
